### ISSUE TITLE
Command filter does not cover capitalization case.

### ISSUE THREAD

**Issue by mibby** [Pwn9/PwnFilter#11]
PwnFilter version 3.3.2-SNAPSHOT-b78

The command filter does not cover capitalization cases. 

```
# Filter commands as well as chat true/false
commandfilter: true
```

```
cmdlist:
- me
```
If a player types /me BLABLABLACURSE, the profanity is removed and the capitalization is lowercased.

If a player types /ME BLABLABLACURSE, the profanity is not removed and the capitalization is not lowercased.

Regex.
```
# REPLACE a list of naughty words with meep!

match cunt|whore|fag|slut|queer|bitch|bastard|fuck|wtf|motherfucker|shit|faggot|penis|nigger|dick|tits|vagina|nigga|pussy|twat|skank|wanker|piss|damn
then deny
then warn &6[&4Filter&6] &cPlease do not use profanity in chat. Your message has been blocked.


# TRIM a single repeated character to 2 repeats maximum
# fixes "aaaaaaaaaaaaa"

match ([^0-9)])(?=\1\1\1\1+)
then replace


# TRIM 2 repeated characters to 2 repeats maximum:
# fixes "hihihihihi"

match ([^0-9][^0-9])(?=\1\1+)
then replace


# TRIM 3 repeated characters to 2 repeats maximum
# fixes "lollollollollol"

match ([^0-9][^0-9][^0-9])(?=\1\1+)
then replace


# REPLACE CAPS!!! New in Version 2.0.0!!!  Yes.. not just block or warn but replace with lower

match (\p{Lu}|\s){6,120}
then lower
```

**Comment by SmallSansSerif** [comment]
Do you have a recent working build of this @mibby ? I am suspecting that the version I am using is creating an occasional max CPU condition that locks the server. Their dev build site is down for some reason.

**Comment by mibby** [comment]
Sorry, no. I use the latest dev build, which is of the latest source compile. This is still broken.

**Comment by ptoal** [comment]
My preliminary testing suggests that this is fixed in the latest dev build.  Can you confirm?
