### ISSUE TITLE
Capitalization filter does not work with PwnFilter dev build 82.

### ISSUE THREAD

**Issue by mibby** [Pwn9/PwnFilter#13]
@ptoal PwnFilter dev build 82.
http://ci.toal.ca/job/PwnFilterDevelopment/82/

The capitalization regex filter does not work with the development build. 
```
# REPLACE CAPS!!! New in Version 2.0.0!!!  Yes.. not just block or warn but replace with lower

match (\p{Lu}|\s){6,120}
then lower
```

Downgrading to normal PwnFilter build 82, it works as intended.
http://ci.toal.ca/job/PwnFilter/82/

**Comment by ptoal** [comment]
Thanks.  This was a regression.  Can you please try the latest dev build (83)?

**Comment by mibby** [comment]
@ptoal Not fixed with dev build 83.

**Comment by ptoal** [comment]
Oh... This is an ugly one.  It was a "fix one bug that was covering for another one".   I think I have finally fixed this.  Build 84 in progress.

**Comment by mibby** [comment]
Finally seems fixed with dev 84. Thanks. :)
