### ISSUE TITLE
1.8.8

### ISSUE THREAD

**Issue by Someone-NEW** [Pwn9/PwnFilter#15]
Can someone update this amazing plugin i love this regex rules i use it now on Spigot 1.8.8 and work perfect but BookAndQuill not filter all lines and pages, please fix that and i hope soon update thanks.
I thin someone are a make reply of that plugin like PandoraChatFilter and is Premium muss be look to code is copy or not and i thin it is a copy. Pandora is a copy ok realy need this update thanks

**Comment by ptoal** [comment]
Book and Quill is next on my todo list.

**Comment by ptoal** [comment]
I had a look at PandoraChat filter.  Not a copy, for sure.  Also, not capable of a great many things that PwnFilter is capable of.  I would say it's targeted for a different audience.

Anyway, as far as I can tell, Book and Quill is now working correctly on 1.8.8, with the latest builds. (-b94)

I will be releasing PwnFilter 3.9.0 today, as soon as I finishing arguing with jenkins/maven release plugin
