### ISSUE TITLE
PwnFilter 1.8.8 or 1.8-19

### ISSUE THREAD

**Issue by Someone-NEW** [Pwn9/PwnFilter#18]
Hi there i only will say that im test all your new versions on 2016 updated and no one has working nothing and i paste here for you one thin i see on console for error plugin does not work so i backup to old one that work on all vesrions and do the job i think you can solve this big issue thank you. I Use Spigot 1.8.8 and one tes server with 1.9 but i use 1.8.8 and i have a problem and problem with book and quills rules not woking thank you

from log paste info: http://pastebin.com/DShAdpJL

**Comment by ptoal** [comment]
Looks like an error in your config.yml.  What do you have in your config.yml for "loglevel: " ?  It looks like you have "then log", which is not a valid config.  Usually, it should be set to "fine", unless you want to see MATCH/SEND entries in your console log, in which case it should be "info".

**Comment by Someone-NEW** [comment]
i dont know but before are all working fine an old version so i think there are on new version changed i send you on bukkit page PM and there you have all my files thank you.

**Comment by ptoal** [comment]
As I expected, your loglevel: line has an invalid value.  Please change it back to "info".

I have added an error message for this, so that the plugin doesn't crash (though it will still disable itself, because that's not a valid configuration).

I suspect older versions simply ignored the error.

Also, as an aside, when sending files to someone for review, a self-extracting executable is a great way to not get someone to look at it.  I would never have run the program, but figured that you had used rar to compress the directory, and extracted it manually.  Most people would simply have deleted your file, suspecting it was a virus or trojan.

**Comment by Someone-NEW** [comment]
Dont Worry its safe and many dont use .rar so im use than self extracting for you or only rar tha i can uploud in 1 file to dropbox

**Comment by ptoal** [comment]
lol.  Don't worry.. _my_ .exe is safe.

I saw your files.  You have an error in your config.yml.  Please fix it, as stated, and try again.

**Comment by Someone-NEW** [comment]
xD hehe ok thank you i newver do something bad so im suprised thank you for fast response i will change this and i will see it will work.

**Comment by Someone-NEW** [comment]
Ok i tested and now all work only now no colorcodes on screen warnings not working i have suggestion to add suport again that colorcodes. Than the second rules on Book&Quils on all lines warnings are not the same you can test you will se what i mean use for example "Bitch" xD

**Comment by ptoal** [comment]
Ok, I think I understand what you are talking about.  I have fixed the bug where the color codes weren't being translated.

As to the "all lines warnings are not the same", I'm not sure what this means?  I did notice you are using multiple "warn" lines, instead of "respond <<EOF", as suggested in the documentation.  Are you referring to the fact that the "warn lines" are not being sent in the correct order, or some other issue.

Instead of doing this:
```
then warn &6&m-----------------------------------------------------&r
then warn &c&lDo not be annoying with that word attempting to circumvent the filter are against the rules.
then warn &c&lDo not use, take or giving social contacts on server!!!
then warn &6&m-----------------------------------------------------&r
```
you should do:
```
then respond <<EOF
&6&m-----------------------------------------------------&r
&c&lDo not be annoying with that word attempting to circumvent the filter are against the rules.
&c&lDo not use, take or giving social contacts on server!!!
&6&m-----------------------------------------------------&r
EOF
```

This will ensure that all your messages get sent in the correct order.

**Comment by ptoal** [comment]
3.9.0 Release is now out.  It's available at spigotmc.org, dev.bukkit.org, and directly from my repo: https://repo.sagely.ca/com/pwn9/PwnFilter/PwnFilter/3.9.0/

**Comment by Someone-NEW** [comment]
But this is a lot of massive custom change on inside of rules for chat signs books etc. that will be a terrible to do that. Why are so drasticaly all changed your plugin? i think all that are not need to be changed. but thanks i better use the old one thats to big changes.

**Comment by ptoal** [comment]
The plugin started as one long string if if/else statements.  Since that time, I have increased it's modularity.  This has been done for a number of reasons, the most important is so that I can add tests for everything, and then be able to refactor parts of the code knowing I haven't broken anything.  The other is to de-couple it from the Bukkit API.  A lot of the problems I've had with the plugin in the past were because it was relying directly on Bukkit calls, which are now abstracted.  Also, by decoupling from Bukkit, it makes it possible for me to make a Sponge plugin, which is one of my next tasks.

If you want to use an older version of the plugin because you are afraid of the new changes, that's understandable.  Even though a lot has changed, the major functions are heavily tested, so the risk should be fairly low.  Also, the plugin is now running on the Pwn9 YASMP server, and I haven't seen any problems so far.

**Comment by Someone-NEW** [comment]
I test and now colorcodes on warnings work great thanks for that. you are awesome.

**Comment by ptoal** [comment]
I don't understand what you mean about Book & Quill being "strange".  I did a test, where I used a book & quill to write a book with one line: "Bitch", and it gave me this:
https://www.dropbox.com/s/w4bl609jvztgcgy/Screenshot%202016-04-19%2010.58.41.png?dl=1

**Comment by Someone-NEW** [comment]
yes but test the same at all line the same that is what i will say sorry for bad English. ;)

**Comment by ptoal** [comment]
I still don't understand.  Can you share a video of what's happening?

**Comment by Someone-NEW** [comment]
o i will try something but can you write the same word "bitch" into the second line this time not in the first line and yopu will see what i mean thank you.

**Comment by ptoal** [comment]
Ok.  I get it now.  I will have a look.

**Comment by Someone-NEW** [comment]
Here is a video: https://www.dropbox.com/s/vqarn6bk8qjkpa7/BookAndQuill.avi?dl=0

**Comment by ptoal** [comment]
It is because of the carriage return. It is not a "word boundary", so the regex is not matching on the \b.

**Comment by Someone-NEW** [comment]
I hope you can finaly fix that and to be books worked with filtering at all ;)

**Comment by ptoal** [comment]
Ok.  I think I may have the problem solved.  Can you try the latest build, here: https://ci.sagely.ca/job/PwnFilter/101/

**Comment by Someone-NEW** [comment]
I tested but is the same problem is not fixing for now. Here is the video is the same problem like here:
https://www.dropbox.com/s/n6jph28895yyajp/BookAndQuill.avi?dl=0

**Comment by ptoal** [comment]
You tested with build 101?  I used your rules with 101, and it works for me.  Strange.

**Comment by Someone-NEW** [comment]
Yes, i will download again and test it carefuly again but will see

**Comment by ptoal** [comment]
I've looked more into it, but I get different results when I try the same things you are doing.  I'm wondering if there may be another plugin that is interacting with the books.

I have made a special build in the Dev tree, which outputs some information about the content of the books to the console. [PwnFilterDevelopment#96](https://ci.sagely.ca/job/PwnFilterDevelopment/96) Can you try this one, and then send me the console logs?  They should look something like this:
```
[2016/04/20 18:04:29] [PwnFilter] i(105)  (32) c(99) a(97) n(110)  (32) u(117) n(110) d(100) e(101) r(114) s(115) t(116) a(97) n(110) d(100) §(167) 0(48)
(10) §(167) 0(48) i(105)  (32) c(99) a(97) n(110)  (32) u(117) n(110) d(100) e(101) r(114) s(115) t(116) a(97) n(110) d(100) §(167) 0(48)
(10) §(167) 0(48)
(10)
```

**Comment by Someone-NEW** [comment]
i have only Essentials some block for use that books but didnt work only messages are, but filtering of rules are now not work for me i use EssentialsX

**Comment by ptoal** [comment]
Sorry, this is the correct build.  The last one failed: [https://ci.sagely.ca/job/PwnFilterDevelopment/97/](https://ci.sagely.ca/job/PwnFilterDevelopment/97/)

**Comment by ptoal** [comment]
I will definitely need to see the output from the Development build.  I can't reproduce the problem here, for some reason.

**Comment by ptoal** [comment]
Erg... I forgot to merge some changes I made to the master branch into the dev branch.  Build #98 has those changes, as well as the debug changes.[PwnFilterDevelopment#98/](https://ci.sagely.ca/job/PwnFilterDevelopment/98/)

**Comment by ptoal** [comment]
Sorry about the build server being down.  It's hosted at a place that isn't known for its reliability, but it is cheap.

I restarted it, and you should be able to download the build in my last comment, (Dev #98) now.

**Comment by Someone-NEW** [comment]
I have download that build and start but i cant in my logs file find that type of INFO like these here.

[2016/04/20 18:04:29] [PwnFilter] i(105)  (32) c(99) a(97) n(110)  (32) u(117) n(110) d(100) e(101) r(114) s(115) t(116) a(97) n(110) d(100) §(167) 0(48)
(10) §(167) 0(48) i(105)  (32) c(99) a(97) n(110)  (32) u(117) n(110) d(100) e(101) r(114) s(115) t(116) a(97) n(110) d(100) §(167) 0(48)
(10) §(167) 0(48)
(10)

**Comment by Someone-NEW** [comment]
So i solve the problem and now here is the info from my log file using "i can understand" for example:

19:00:32] [Server thread/INFO]: [PwnFilter] i(105)  (32) c(99) a(97) n(110)  (32) u(117) n(110) d(100) e(101) r(114) s(115) t(116) a(97) n(110) d(100) 
[19:00:55] [Server thread/INFO]: [PwnFilter] 
(10) §(167) 0(48) i(105)  (32) c(99) a(97) n(110)  (32) u(117) n(110) d(100) e(101) r(114) s(115) t(116) a(97) n(110) d(100) 

I hope you can fix that

**Comment by Someone-NEW** [comment]
I muss report an** i use again the BUILD 101** and test it again and **all work great now normaly** work all so im muss **sorry about my mistake** whily i fint that i have 2 the same plugins on my folder **PwnFilter and PfnFilterOLD** so this is removed and build 101 work again like expected so this is now fixed id im sorry about this mistake. When i foud somethin i will report again. Thank you for fast response about this problem.

**Comment by ptoal** [comment]
Ok.  Build 101 is the best one to use right now, then.  I will release a 3.9.1 in a week or so, with this fix in it.
