### ISSUE TITLE
Update for 1.12????????

### ISSUE THREAD

**Issue by Ironic8b498** [Pwn9/PwnFilter#28]
I have notice that pwnfilter works but can not run and commands like comment, kick, ban, etc. Not sure if it's the filter or me I also noticed the cap filter is not changing to lower case, rest of filter filters swears, replaces or removes. just won't punish players

**Comment by Someone-NEW** [comment]
Yea this is one of the biggest bug/issue not updated.

**Comment by msudol** [comment]
PwnFilter development has stalled for quite some time, it looks like since the last release some changes have been made to bukkit/spigot that are starting to break this plugin. Unfortunately, there are no plans at this time to update for the latest versions of Minecraft.
